---
- name: AWX Inventory Test
  hosts: all
          ansible_host: 10.0.5.51   # Management IP of the CML switch
          ansible_user: admin             # CML switch username
          ansible_password: admin123     # CML switch password
          ansible_network_os: cisco.ios.ios
          ansible_connection: network_cli
